### ISSUE TITLE
解析错误

### ISSUE THREAD

**Issue by zhangweihong** [marmot-z/canal-nodejs#3]
----------------------
Connect cancal server occur error RangeError: index out of range: 13548 + 1 > 13548
    at indexOutOfRange (D:\Download\canal-nodejs-master\node_modules\protobufjs\src\reader.js:13:12)
    at BufferReader.skip (D:\Download\canal-nodejs-master\node_modules\protobufjs\src\reader.js:344:23)
    at BufferReader.Reader.skipType (D:\Download\canal-nodejs-master\node_modules\protobufjs\src\reader.js:358:18)
    at Type.Messages$decode [as decode] (eval at Codegen (D:\Download\canal-nodejs-master\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:19:5)
    at Function.decode (D:\Download\canal-nodejs-master\src\proto-util.js:55:28)
    at Function.deserializer (D:\Download\canal-nodejs-master\src\canal-message-deserializer.js:15:42)
    at D:\Download\canal-nodejs-master\src\simple-canal-connector.js:170:66
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by zhangweihong** [comment]
![image](https://user-images.githubusercontent.com/6658343/189835290-6b7cbc89-3443-45a6-b0a3-c62695c60b88.png)
看了下buffer最后几位只要都是0就会报解析错误，在 D:\Download\canal-nodejs-master\node_modules\protobufjs\src\reader.js
343行修正>= 为>就可以正确解析

**Comment by marmot-z** [comment]
感谢你的反馈
